version: '2'

services:

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
      args:
        VERSION: 0.2
    image: agaveplatform/jupyter-notebook
    command: start-notebook.sh --NotebookApp.token=''
    mem_limit: 2048m
    ports:
      - '8888:8005'
    environment:
      - 'VM_MACHINE=$VM_MACHINE'
      - 'VP_IPADDRESS=$VP_IPADDRESS'
      - 'USE_TUNNEL=True'
    volumes:
      - training-volume:/home/jovyan/work
      #- ./sandbox/ssh:/home/jovyan/.ssh:ro
      - $HOME/.agave:/home/jovyan/.agave
      - ../notebooks:/home/jovyan/notebooks:ro

  sandbox:
    build:
      context: ./sandbox
      dockerfile: Dockerfile
      args:
        VERSION: 0.2
    image: agaveplatform/sc17-sandbox
    mem_limit: 2048m
    privileged: True
    ports:
      - '10022:22'
    environment:
      - 'VM_MACHINE=$VM_MACHINE'
      - 'VP_IPADDRESS=$VP_IPADDRESS'
      - 'USE_TUNNEL=True'
    volumes:
      - training-volume:/home/jovyan/work
      - $HOME/.agave:/home/jovyan/.agave
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  training-volume:
